  
kubernetes:
  enabled: true
  accounts:
  - name: ali-prod
    requiredGroupMembership: []
    providerVersion: V2
    permissions: {}
    dockerRegistries: []
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces: []
    omitNamespaces: []
    kinds: []
    omitKinds: []
    customResources: []
    cachingPolicies: []
    kubeconfigFile: configserver:kubeconfig.yml
    oAuthScopes: []
    onlySpinnakerManaged: false
  primaryAccount: ali-prod
